df=read.csv("pokemon.csv")
View(df)
nrow(df)
ncol(df)
table(df$Legendary)
table(df$Type.1)
table(df$Type.2)
table(df$Generation)
min(df$HP)
max(df$HP)
min(df$Speed)
max(df$Speed)
is.na(df$Type.1)
is.na(df$Type.2)
sum(is.na(df$Type.1))
sum(is.na(df$Type.2))
colnames(df)
colnames(df)[colnames(df)=='Type.1']<-"primary_type"
View(df)
colnames(df)[colnames(df)=='Type.2']<-"secondary_type"
df %>% filter(df$primary_type=='Grass')->grass_pokemon
View(grass_pokemon)
min(grass_pokemon$Speed)
max(grass_pokemon$Speed)

mean(grass_pokemon$Attack)
mean(grass_pokemon$Sp..Atk)

library(ggplot2)
ggplot(data=grass_pokemon,aes(x=HP))+geom_histogram()
ggplot(data=grass_pokemon,aes(x=Attack))+geom_histogram()
ggplot(data=grass_pokemon,aes(x=Speed))+geom_histogram()
ggplot(data=grass_pokemon,aes(x=Legendary))+ geom_bar()
ggplot(data=grass_pokemon,aes(x=Generation,fill=as.factor(Generation)))+geom_bar()
